version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "loganharbour"
    ignore:
      - dependency-name: "Django"
        versions: [">=5.0,<6.0"]
